# Module 2 Pandas

## Section 2.A Pandas Basics

In [2]:
import numpy as np
import pandas as pd

### 2.A.2 pandas Series

- A Series is a 1D arrray that can hold data of any type
    - Think of it likes a column in a table
    - Values are indexed by default, but can be labelled

In [3]:
list_x = [2,3,4,5,6,7] # Could even hold strings: 'a', 'b'

x = pd.Series(list_x)

x

0    2
1    3
2    4
3    5
4    6
5    7
dtype: int64

In [4]:
y = pd.Series(list_x, index = [1, 2, 3, 4, 5, 6]) # Index could even be: ['a', 'b', 'c', ...]
y

1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

- A series can also be created from a dictionary of key-value pairs

In [5]:
dict_x = { # key --> is the index, 
    1: 2,
    2: 3,
    3: 4,
    4: 5,
    5: 6,
    6: 7
}

z = pd.Series(dict_x) # using a dictionary to create a Series results in the index taking the key labels
z

1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

### 2.A.3 pandas DataFrame

- 2D data structures in pandas are known as **DataFrame**
    - It is also like a table 
    - Series can be combined to create a DataFrame, or DataFrame can be created from a dictionary

In [6]:
# In-class example:
dict_x = { # key --> is the index, 
    '1': (2,),
    '2': 3,
    '3': 4,
    '4': 5,
    '5': 6,
    '6': 7
}

df_x = pd.DataFrame(dict_x)
print(df_x)

   1  2  3  4  5  6
0  2  3  4  5  6  7

In [7]:
# More examples:
data = {
    "product_num": [1658, 2476, 3911],
    "quantity": [120, 54, 98]
}

inventory = pd.DataFrame(data, index = [1,2,3])
print(inventory)

   product_num  quantity
1         1658       120
2         2476        54
3         3911        98

In [8]:
# You can locate a specific index
inventory.loc[[0]] ## double brackets retrieves as DataFrame

KeyError: "None of [Index([0], dtype='int64')] are in the [index]"

In [ ]:
# How to retrieve values of a column
inventory[['product_num']] # or inventory.columnName

   product_num
0         1658
1         2476
2         3911

### 2.A.4 Creating a DataFrame

- Dataframes can be created from collections: list, tuples, NumPy arrays, or pandas Series, or imported files

In [ ]:
# Example: 1D examples
df01 = pd.DataFrame((1,2,3,4))

arr = np.array([1,2,3,4])

ser = pd.Series(arr)
df03 = pd.DataFrame(ser)

df03

   0
0  1
1  2
2  3
3  4

- A DataFrame from a 2D array has columns and rows:

In [ ]:
arr2 = np.array([[1,2,3,4]])
df02 = pd.DataFrame(arr2)
df02

   0  1  2  3
0  1  2  3  4

### 2.A.5 Inserting columns into a DataFrame

- **.insert()** can be used to add columns, specifying the index position, column name, and source/value

In [ ]:
# Example:
df01 = pd.DataFrame((1,2,3,4))
df01.insert(1, 1, [20,20,20,20]) #insert(Index pos, column name, values)
df01

   0   1
0  1  20
1  2  20
2  3  20
3  4  20

### 2.A.6 NumPy sampling in a DataFrame

- To generate a sample DataFrame:
    - **.arange()** function to generate a number ranfe to populate values
    - **.reshape()** to specify how to arrange data into rows and columns

In [ ]:
# Example:
sampledata = pd.DataFrame(np.arange(8).reshape((2,4)),
                            index = ['apple', 'banana'],
                            columns = ['a','b','c','c'])

print(sampledata)

        a  b  c  c
apple   0  1  2  3
banana  4  5  6  7

### 2.A.7 Indexing of DataFrames

- By default, rows are indexed with 0
- Labels can be added into DataFrame index

In [ ]:
# Example:
rowdata = {'col1': [715,651], 'col2': [414,612]}
areacodes = pd.DataFrame(rowdata, index = ['WI', 'MN'])

print(areacodes)

    col1  col2
WI   715   414
MN   651   612

- Row data can be retrieved by slicing the index

In [ ]:
print(areacodes['MN':])

    col1  col2
MN   651   612

### 2.A.8 Accessing rows by .loc[] and .iloc[]

- Use **.loc[]** attribute to access a set of rows by index

In [ ]:
data = {
    "product_num": [1658, 2476, 3911],
    "quantity": [120, 54, 98]
}

inventory = pd.DataFrame(data)
print(inventory)

   product_num  quantity
0         1658       120
1         2476        54
2         3911        98

- A single row (here, row 0) is returned as a series

In [ ]:
inventory.loc[0]

product_num    1658
quantity        120
Name: 0, dtype: int64

- Multiple rows (here, rows[1,2]) are returned as a DataFrame

In [ ]:
inventory.loc[[1,2]]

   product_num  quantity
1         2476        54
2         3911        98

- A new row can also be assigned to a DataFrame use .loc()

In [ ]:
inventory.loc[3] = [7878, 0]
inventory

   product_num  quantity
0         1658       120
1         2476        54
2         3911        98
3         7878         0

- If the DataFrame uses a named index, the integer index can still be accessed using **.iloc[]**

### 2.A.9 Reading files into a DataFrame

- If a dataset is stored in a file, pandas can be used to import the data into a DataFrame

- Example:
    - import pandas as pd   # First step is always to import
    - df1 = pd.read_[csv, excel, json, etc]('file name.ext)

- You can also write a DataFrame to a file

- Example:
    - df1.to_[csv, excel, etc]('filename.ext', index=false)
    - df.to_json('filename.json')

### 2.A.10 Generating info about the DataFrame

- To preview only the first / last records from a DataFrame:
    - **.head()** displays the header and first n rows (5 by default)
    - **.tail()** displays the last n rows (5 by default)
- To see statistics on numerica columns, use **.describe()**:

In [ ]:
sales_det = pd.DataFrame({
    "prod_num": [658, 2476, 658, 2476, 3911, 3911],
    "price": [7.89, 5.49, 7.89, 5.49, 6.25, 6.25]
})

sales_det
sales_det.describe().round(2) # rounded just for better reading

       prod_num  price
count      6.00   6.00
mean    2348.33   6.54
std     1458.14   1.10
min      658.00   5.49
25%     1112.50   5.68
50%     2476.00   6.25
75%     3552.25   7.48
max     3911.00   7.89

### 2.A.11 More tools to explore the DataFrame

- To see a frequency count of each unique value in a columns, use **.value_counts()**
    - Useful for categorical columns

In [ ]:
sales_det['prod_num'].value_counts()

prod_num
658     2
2476    2
3911    2
Name: count, dtype: int64

## Section 2.B Cleaning data with pandas

### 2.B.1 Removing rows or columns

- To drop records from a DataFrame
    - Use **drop()**
        - axis = 0: refers to rows
        - axis = 1: refers to columns
    - **dropna()** removes rows containing NaN values

- For identifying and dealing with duplicates / nonunique records:
    - **duplicated()** identifies duplicates
    - To remove dupes, use **drop_duplicates()** 
    - example_df.drop_duplicates()

- Option argument **inplace = True** will not return a new DataFrame, but instead modify the original DataFrame

### 2.B.2 Filter rows

- Conditional logic can be used to **filter rows** in a DF and add them to a new DF

In [ ]:
inventory = pd.DataFrame({
    "prod_num": [1658, 2476, 3911],
    "quantity": [ 120, 54, 98]
})
print(inventory)

inv_filter = inventory[(inventory['quantity'] < 100)]
print(inv_filter)

   prod_num  quantity
0      1658       120
1      2476        54
2      3911        98
   prod_num  quantity
1      2476        54
2      3911        98

### 2.B.3 Replace values in a DataFrame

- The **replace()** method replaces specified values with new values

In [9]:
# Syntax:

# df_name.replace(to_replace, value, [inplace = false]) # False by default

# Example:
inventory.replace('prod_name', {1658: 658}, inplace = True)
inventory

   product_num  quantity
1         1658       120
2         2476        54
3         3911        98

- To replace NaN values, use **fillna()**

In [ ]:
# for all NaN values in DF
inventory = inventory.fillna(130)

# for just NaN values in a specified column
inventory['prod_name'] = inventory.prod_num.fillna(130)

### 2.B.4 Fixing bad data with .loc[] or .drop[]

In [12]:
inventory = pd.DataFrame({
    "prod_num": [1658, 2476, 3911],
    "quantity": [ 120, 54, 98]
})

# Using .loc[] to assign a new value:
inventory.loc[2, "quantity"] = 100

inventory

   prod_num  quantity
0      1658       120
1      2476        54
2      3911       100

- Using .loc[] and .index attribute to loop through rows and assign new values based on a condition:

In [ ]:
for x in inventory.index:
    if inventory.loc[x, "quantity"] < 100:
        inventory.loc[x, "quantity"] = 100

### 2.B.5 Retrieving & changing column data

- Columns can be accessed using dictionary-like notation or by using dot attribute notation

In [ ]:
# Example 1: Column name written in dictionary-like notation
rowdata = {'col1': [715,651], 'col2': [414,612]}
areacodes = pd.DataFrame(rowdata, index = ['WI', 'MN'])
print(areacodes)
print() # line break
print(areacodes['col1'])

    col1  col2
WI   715   414
MN   651   612

WI    715
MN    651
Name: col1, dtype: int64

In [16]:
# Example 2: Column name using dot notation
# using the same Df from example 1

print(areacodes.col1)

WI    715
MN    651
Name: col1, dtype: int64

- Columns can be added, or columns values updated, by using the (=)

In [17]:
# Using same DF from above
areacodes['col3'] = [262, 218]
print(areacodes)

    col1  col2  col3
WI   715   414   262
MN   651   612   218

## Section 2.C Working with data in pandas

### 2.C.1 Basic Aggregatings

- Common aggregation functions include:
    - Sum()
    - Count()
    - mean()
    - median()
    - min() and max()
- **.aggregation()** method allows multiple aggregation to performed at once, and can speciy columns and functions to perform

### 2.C.2 Using groupby()

- The **groupby()** function reshapes a DF into groups based on specified creiteria. Involves splitting, apply a function and combining the results
    - Useful for grouping large amount of data and computing on them

In [19]:
# Example:
sales_det = pd.DataFrame({
    "prod_num": [658, 2476, 658, 2476, 3911, 3911],
    "price": [7.89, 5.49, 7.89, 5.49, 6.25, 6.25]
})
print(sales_det)

sales = sales_det.groupby(['prod_num']).mean()
print(sales)

   prod_num  price
0       658   7.89
1      2476   5.49
2       658   7.89
3      2476   5.49
4      3911   6.25
5      3911   6.25
          price
prod_num
658        7.89
2476       5.49
3911       6.25

### 2.C.3 Sorting data in a DF

- **.sort_index()** to sort lexicographically by row or column label

In [23]:
sampledata = pd.DataFrame(np.arange(8).reshape((2,4)),
                            index = ['cantaloupe', 'banana'],
                            columns = ['d','a','b','c'])

print(sampledata)

print(sampledata.sort_index(axis = 'columns'))
print(sampledata.sort_index())

            d  a  b  c
cantaloupe  0  1  2  3
banana      4  5  6  7
            a  b  c  d
cantaloupe  1  2  3  0
banana      5  6  7  4
            d  a  b  c
banana      4  5  6  7
cantaloupe  0  1  2  3

- To sort by column values, use the **.sort_values()** method and column name(s)

### 2.C.4 Ranking data

- The **rank()** method assigns each value in a series or DF a rank from 1 through the total number of valid data points

In [29]:
rowdata = {'col1': [414,651], 'col2': [715,612]}
areacodes = pd.DataFrame(rowdata, index = ['WI', 'MN'])
areacodes['col3'] = [262, 218]
print(areacodes)

    col1  col2  col3
WI   414   715   262
MN   651   612   218

In [30]:
print(areacodes.rank(axis='columns'))

    col1  col2  col3
WI   2.0   3.0   1.0
MN   3.0   2.0   1.0

In [31]:
print(areacodes.rank(axis='rows'))

    col1  col2  col3
WI   1.0   2.0   2.0
MN   2.0   1.0   1.0

### 2.C.5 Merging DF

- The **merge()** function can be used to merge two or more DF based on multiple common columns

In [34]:
inventory = pd.DataFrame({
    "prod_num": [658, 2476, 3911],
    "quantity": [120, 54, 98]
})

sales_det = pd.DataFrame({
    "prod_num": [658, 2476, 658, 2476, 3911, 3911],
    "price": [7.89, 5.49, 7.89, 5.49, 6.25, 6.25]})
sales = sales_det.groupby(['prod_num']).mean()

merged_df = pd.merge(inventory, sales, on=['prod_num'])
print(merged_df)

merged_df2 = pd.merge(inventory, sales_det, on=['prod_num'])
print(merged_df2)

   prod_num  quantity  price
0       658       120   7.89
1      2476        54   5.49
2      3911        98   6.25
   prod_num  quantity  price
0       658       120   7.89
1       658       120   7.89
2      2476        54   5.49
3      2476        54   5.49
4      3911        98   6.25
5      3911        98   6.25