# Exercise 2.C Working with multiple DataFrames

In [21]:
import numpy as np
import pandas as pd

## Basic Aggregations

Create a DataFrame named df_sales using the following data:

In [22]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
    'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

Add a new column Revenue to df_sales by multiplying Units_Sold and Price

In [23]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

Use the sum function to calculate the total Units_Sold and total Revenue across all
products and regions

In [24]:
df_sales[['Units_Sold', 'Revenue']].agg('sum')

Units_Sold      105
Revenue       16000
dtype: int64

Use the mean function to calculate the average Units_Sold and average Revenue.

In [25]:
df_sales[['Units_Sold', 'Revenue']].agg('mean').round(2)

Units_Sold      11.67
Revenue       1777.78
dtype: float64

## Grouping Data

Use the groupby function to group df_sales by Product and calculate the total
Units_Sold and total Revenue for each product

In [28]:
df_sales.groupby(['Product'])[['Units_Sold', 'Revenue']].agg('sum')

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

Use the groupby function to group df_sales by Region and calculate the average Units_Sold and average Revenue for each region.

In [29]:
df_sales.groupby(['Region'])[['Units_Sold', 'Revenue']].agg('mean')

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

Use the groupby function to group df_sales by both Product and Region and calculate the sum of Units_Sold and Revenue for each combination

In [30]:
df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].agg('sum')

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

Sort df_sales by Units_Sold in ascending order

In [34]:
df_sales.sort_values('Units_Sold', ascending = False)

  Product Region  Units_Sold  Price  Revenue
2       C   East          20    150     3000
8       C  North          15    150     2250
1       B  South          15    200     3000
5       C  South          15    150     2250
0       A  North          10    100     1000
6       A   East          10    100     1000
4       B  North          10    200     2000
3       A   West           5    100      500
7       B   West           5    200     1000

Sort df_sales by Revenue in descending order

In [35]:
df_sales.sort_values('Revenue', ascending = False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

Add a new column Revenue_Rank to df_sales, which ranks the Revenue values in descending order (i.e., highest revenue has rank 1).

In [46]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending = False, method = 'dense').astype(int)
df_sales['Revenue_Rank']
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000             4
1       B  South          15    200     3000             1
2       C   East          20    150     3000             1
3       A   West           5    100      500             5
4       B  North          10    200     2000             3
5       C  South          15    150     2250             2
6       A   East          10    100     1000             4
7       B   West           5    200     1000             4
8       C  North          15    150     2250             2

## Merging DataFrames

Create a new DataFrame named df_products with the following data:

In [50]:
product_data = {'Product': ['A', 'B', 'C'],
'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)

df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

Merge df_sales with df_products on the Product column, resulting in a new DataFrame named df_merged

In [53]:
df_merged = pd.merge(df_sales, df_products, on = ['Product'])
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000             4  Electronics
1       B  South          15    200     3000             1    Furniture
2       C   East          20    150     3000             1   Appliances
3       A   West           5    100      500             5  Electronics
4       B  North          10    200     2000             3    Furniture
5       C  South          15    150     2250             2   Appliances
6       A   East          10    100     1000             4  Electronics
7       B   West           5    200     1000             4    Furniture
8       C  North          15    150     2250             2   Appliances

Use groupby on df_merged to calculate the total Revenue by Category

In [54]:
df_merged.groupby(['Category'])['Revenue'].agg('sum')

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64